import React from "react";
import Head from "next/head";
import Header from "../components/Header";
import Footer from "../components/Footer";
import AboutSlides from "../components/AboutSlides";

export default function about() {
  return (
    <div>
      <Head>
        <title>About - NFTD EARTH</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1"
        />
      </Head>

      <Header />

      <main>
        {/* Page title */}
        <section className="relative pt-24 lg\:pb-96">
          <picture className="pointer-events-none absolute inset-0 -z-10 dark:hidden">
            <img
              src="img/gradient_light.jpg"
              alt="gradient"
              className="h-full w-full"
            />
          </picture>
          <div className="container">
            {/* Page Title */}
            <div className="mx-auto max-w-2xl py-16 text-center">
              <h1 className="font-display text-jacarta-700 mb-8 text-4xl font-medium dark:text-white">
                NFTD STABLECOIN
              </h1>
              <p className="dark:text-jacarta-300 text-lg leading-normal">
                YIELD BEARING STABLECOIN BACKED BY STAKED ETH DECENTRALIZED,
                PERMISSIONLESS, TRUSTLESS, ON SIDE CHAIN. ROLLUP APP SPECIFIC
                CHAIN.
              </p>
            </div>
            
            {/* Slider */}
            <AboutSlides/>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
}
